# Generated by Django 4.1.5 on 2023-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4, verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('average_salary_for_name', models.FloatField(verbose_name='Средняя зарплата - DevOps')),
                ('vacancies_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('vacancies_count_for_name', models.IntegerField(verbose_name='Количество вакансий - DevOps')),
            ],
        ),
    ]
