# Generated by Django 4.1.5 on 2023-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_statisticbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4, verbose_name='Город')),
                ('average_salary', models.FloatField(verbose_name='Уровень зарплат по городам')),
                ('proportion', models.FloatField(verbose_name='Доля вакансий по городам')),
            ],
        ),
    ]
