# Generated by Django 4.1.5 on 2023-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_statisticbycity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticbycity',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Город'),
        ),
    ]
